#pragma once

#include "isr.h"

#define PIC_MASTER_COMMAND_PORT 0x20
#define PIC_MASTER_DATA_PORT 0x21
#define PIC_SLAVE_COMMAND_PORT 0xA0
#define PIC_SLAVE_DATA_PORT 0xA1

#define PIC_INIT_COMMAND 0x11
#define PIC_EOI_COMMAND 0x20 // End of interrupt command - MUST BE SENT AFTER PROCESSING THE IRQs!

#define PIC_MASTER_VECTOR_OFFSET 0x20
#define PIC_SLAVE_VECTOR_OFFSET 0x28

#define PIC_SLAVE_IRQ_NO 0x04           // (0000 0100)
#define PIC_SLAVE_CASCADE_IDENTITY 0x02 // (0000 0010)

#define PIC_8086_MODE 0x01

#define PIC_SLAVE_STARTING_IRQ_VECTOR IRQ8